project-tracker-frontend/src/App.css
project-tracker-frontend/src/components/create-project/create-project.css
project-tracker-frontend/src/components/create-project/create-project.jsx
project-tracker-frontend/src/components/navbar/navbar.css
project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/components/project-grid/project-grid.css
project-tracker-frontend/src/components/project-grid/project-grid.jsx
project-tracker-frontend/src/components/sidebar/sidebar.css
project-tracker-frontend/src/components/sidebar/sidebar.jsx
project-tracker-frontend/src/components/unselected-container/unselected-container.css
project-tracker-frontend/src/components/unselected-container/unselected-container.jsx
project-tracker-frontend/src/pages/Error.jsx
project-tracker-frontend/src/pages/Home.jsx

Added components

---

project-tracker-frontend/src/components/create-project/create-project.css
project-tracker-frontend/src/components/project-grid/project-grid.css
project-tracker-frontend/src/components/project-grid/project-grid.jsx
project-tracker-frontend/src/components/sidebar/sidebar.css
project-tracker-frontend/src/components/sidebar/sidebar.jsx
project-tracker-frontend/src/components/unselected-container/unselected-container.css

Added components to change board and made ui mui friendly

---

project-tracker-frontend/src/components/project-grid/project-grid.css
project-tracker-frontend/src/components/sidebar/sidebar.css

Impoved mobile friendliness

---

project-tracker-frontend/src/components/create-project/create-project.jsx
project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/components/unselected-container/unselected-container.jsx
project-tracker-frontend/src/pages/Login.jsx

Updated create and edit project to fit api

---

SQL/V3__UpdateProjectLinkColumns.sql
project-tracker-frontend/src/components/create-project/create-project.jsx
project-tracker-frontend/src/components/navbar/navbar.jsx

Fix project table null issue

---

project-tracker-frontend/src/components/project-grid/project-grid.jsx
project-tracker-frontend/src/pages/Home.jsx

Removed test token

---

project-tracker-frontend/src/components/create-project/create-project.jsx
project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/components/project-grid/project-grid.jsx
project-tracker-frontend/src/pages/Home.jsx

create project functional, used oauth token

---

project-tracker-frontend/src/components/create-project/create-project.jsx
project-tracker-frontend/src/pages/Home.jsx

Made responses to creating a project

---

project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/components/unselected-container/unselected-container.css
project-tracker-frontend/src/components/unselected-container/unselected-container.jsx

hide nav text on small screen

---

project-tracker-frontend/src/components/buttons/login-button.jsx
project-tracker-frontend/src/components/login-card/login-card.jsx
project-tracker-frontend/src/main.jsx
project-tracker-frontend/src/pages/Login.jsx

made login page responsive

---

project-tracker-frontend/index.html

updated title and icon

---

project-tracker-frontend/src/components/buttons/login-button.jsx
project-tracker-frontend/src/components/login-card/login-card.jsx
project-tracker-frontend/src/theme.jsx

joseph card changes

---

project-tracker-frontend/package.json

Possible deployment fix

---

project-tracker-frontend/package-lock.json
project-tracker-frontend/package.json
project-tracker-frontend/src/components/buttons/login-button.jsx
project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/main.jsx
project-tracker-frontend/src/pages/Home.jsx
project-tracker-frontend/src/pages/Login.jsx

possible fix

---

project-tracker-frontend/src/pages/Error.jsx

redirect to home

---

project-tracker-frontend/src/components/navbar/navbar.jsx

added frontend calls for project

---

project-tracker-frontend/src/components/navbar/navbar.jsx

fix undefined data

---

project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/components/project-grid/project-grid.jsx

Fixed endpoint calls and added error messages

---

project-tracker-frontend/src/components/navbar/navbar.jsx

Added admin check and ability to add members

---

project-tracker-frontend/src/components/navbar/navbar.jsx

Error handling and dialogs

---

project-tracker-frontend/src/components/create-project/create-project.jsx
project-tracker-frontend/src/components/navbar/navbar.jsx
project-tracker-frontend/src/components/project-grid/project-grid.css
project-tracker-frontend/src/components/project-grid/project-grid.jsx
project-tracker-frontend/src/pages/Home.jsx

project edit refresh, create spam fix

---

Server/app.js
project-tracker-frontend/src/components/project-grid/project-grid.jsx

Updated rate limit and linked new boards backend

---

project-tracker-frontend/src/components/navbar/navbar.jsx

remove user fix

---

project-tracker-frontend/src/components/login-card/login-card.jsx
project-tracker-frontend/src/components/navbar/navbar.jsx

Unselect project when its removed or deleted

---

project-tracker-frontend/src/components/project-grid/project-grid.css

table head colour

---

project-tracker-frontend/src/components/navbar/navbar.jsx

remove toolbar wrapping
